name: google_map
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.7.1
  flutter_svg: ^2.0.10+1
  location: ^7.0.0
  cupertino_icons: ^1.0.6
  geolocator: ^13.0.1
  material_floating_search_bar_2: ^0.5.0
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  uuid: ^4.5.1
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/map_style/map_style.json
    - assets/map_style/map_style_night.json
    - assets/images/

